#!/usr/bin/env bash

source ./extras/versions.sh

sfile=extras/aws_upload.sh

#	[ -f ${sfile} ] && rm ${sfile}
echo "# autogenerated script to upload elf compiler tool chain to AWS" > ${sfile}

find extras/build/tools/linux32   -name "*${GCC_VER}*" -exec echo  "s3cmd put --acl-public {} s3://energiaUS/tools/linux32/" >> ${sfile} \;
find extras/build/tools/linux64   -name "*${GCC_VER}*" -exec echo  "s3cmd put --acl-public {} s3://energiaUS/tools/linux64/" >> ${sfile} \;
find extras/build/tools/macosx    -name "*${GCC_VER}*" -exec echo  "s3cmd put --acl-public {} s3://energiaUS/tools/macosx/" >> ${sfile} \;
find extras/build/tools/windows   -name "*${GCC_VER}*" -exec echo  "s3cmd put --acl-public {} s3://energiaUS/tools/windows/" >> ${sfile} \;
find extras/build/tools/windows64 -name "*${GCC_VER}*" -exec echo  "s3cmd put --acl-public {} s3://energiaUS/tools/windows64/" >> ${sfile} \;

echo "" >> ${sfile}

find extras/build/cores -name "*${ENERGIA_VER}*" -exec echo  "s3cmd put --acl-public {} s3://energiaUS/cores/" >> ${sfile} \;

echo "" >> ${sfile}

find extras/build/ -name "package_msp430_elf_GCC_index.json" -exec echo  "s3cmd put --acl-public {} s3://energiaUS/packages/" >> ${sfile} \;

